model_name: "gpt2"
output_dir: "outputs/lora"
data_path: "data_legal.csv"
max_length: 256
batch_size: 2
epochs: 1
mlflow_uri: "file:mlruns"
experiment_name: "lora_legal"
run_name: "lora-gpt2-legal"
lora:
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
